# Generated by Django 5.1.3 on 2024-11-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='default/category.jpg', null=True, upload_to='categories/'),
        ),
    ]
