# Generated by Django 5.1.3 on 2024-12-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_order_address_order_city_order_country_order_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
