# Generated by Django 5.1.3 on 2025-01-06 05:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_coupon_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='coupon',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
