# Generated by Django 5.1.3 on 2025-01-04 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_myorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myorder',
        ),
    ]
