# Generated by Django 5.1.3 on 2024-12-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_email_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.AddField(
            model_name='address',
            name='house_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
