# Generated by Django 5.1.3 on 2025-01-01 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_address_city_address_house_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='house_name',
        ),
    ]
