# Generated by Django 5.1.3 on 2025-01-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_address_house_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
